class WeaponShops {

	//CIV
	class gun
	{
		name = "Gun Store";
		side = "civ";
		license = "gun";
		level = -1;
		msg = "Vous n'avez pas la licence de tir !";
		items[] =
		{
			{ "hgun_ACPC2_F", "", 4500 },
			{ "hgun_Pistol_heavy_01_F", "", 3750 },
			{ "hgun_Pistol_heavy_02_F", "", 7500 },
			{ "hgun_Rook40_F", "", 7500 },
			{ "hgun_P07_F", "", 7500 },
			{ "arifle_SDAR_F", "", 18000 },
			{ "SMG_02_F", "", 18000 },
			{ "optic_Aco", "", 750 },
			{ "9Rnd_45ACP_Mag", "", 300 },
			{ "11Rnd_45ACP_Mag", "", 375 },
			{ "6Rnd_45ACP_Cylinder", "", 375 },
			{ "16Rnd_9x21_Mag", "", 750 },
			{ "30Rnd_9x21_Mag", "", 1500 },
			{ "20Rnd_556x45_UW_mag", "", 1200 },
			{ "30Rnd_556x45_Stanag", "", 1800 }
		};
	};
	//REB
	class rebel
	{
		name = "Armurerie Rebelle";
		side = "civ";
		license = "rebel";
		level = -1;
		msg = "Vous n'avez pas la licence Rebelle ($2,500,000) !";
		items[] =
		{
			{ "SmokeShell", "", 50 },
			{ "HandGrenade_Stone","Flash", "", 300 },
			{ "MiniGrenade", "", 300 },
			{ "hgun_ACPC2_F", "", 1000 },
			{ "hgun_Pistol_heavy_01_F", "", 1250 },
			{ "hgun_Pistol_heavy_02_F", "", 2500 },
			{ "hgun_Rook40_F", "", 2500 },
			{ "hgun_P07_F", "", 2500 },
			{ "hgun_PDW2000_F", "", 3500 },
			{ "SMG_01_F", "", 4500 },
			{ "SMG_02_F", "", 6000 },
			{ "arifle_SDAR_F", "", 6000 },
			{ "arifle_TRG20_F", "", 7500 },
			{ "arifle_TRG21_F", "", 8000 },
			{ "arifle_TRG21_GL_F", "", 9500 },
			{ "arifle_Mk20C_F", "", 8000 },
			{ "arifle_Mk20_F", "", 8500 },
			{ "arifle_Mk20_GL_F", "", 10000 },
			{ "arifle_Katiba_C_F", "", 14000 },
			{ "arifle_Katiba_F", "", 16500 },
			{ "arifle_MXC_F", "", 14000 },
			{ "arifle_MX_F", "", 15000 },
			{ "arifle_MX_SW_F", "", 22500 },
			{ "arifle_MXM_F", "", 16500 },
			{ "LMG_Mk200_F", "", 37500 },
			{ "srifle_EBR_F", "", 42500 },
			{ "srifle_LRR_F", "", 65000 },
			{ "optic_Aco", "", 250 },
			{ "optic_Holosight", "", 300 },
			{ "optic_Arco", "", 450 },
			{ "optic_SOS", "", 1000 },
			{ "acc_flashlight", "", 200 },
			{ "acc_pointer_IR", "", 250 },
			{ "9Rnd_45ACP_Mag", "", 100 },
			{ "11Rnd_45ACP_Mag", "", 125 },
			{ "6Rnd_45ACP_Cylinder", "", 125 },
			{ "30Rnd_45ACP_Mag_SMG_01", "", 175 },
			{ "16Rnd_9x21_Mag", "", 250 },
			{ "30Rnd_9x21_Mag", "", 500 },
			{ "20Rnd_556x45_UW_mag", "", 400 },
			{ "30Rnd_556x45_Stanag", "", 600 },
			{ "30Rnd_65x39_caseless_green", "", 750 },
			{ "30Rnd_65x39_caseless_mag", "", 750 },
			{ "100Rnd_65x39_caseless_mag", "", 2700 },
			{ "1Rnd_HE_Grenade_shell", "", 50 },
			{ "UGL_FlareWhite_F", "", 50 },
			{ "1Rnd_Smoke_Grenade_shell", "", 50 },
			{ "200Rnd_65x39_cased_Box", "", 2750 },
			{ "20Rnd_762x51_Mag", "", 2000 },
			{ "7Rnd_408_Mag", "", 1500 }
		};
	};
	class rebelT
	{
		name = "Armurerie Rebelle *provisoire";
		side = "civ";
		license = "rebelT";
		level = -1;
		msg = "Vous n'avez pas la licence Rebelle (Prix: $2,500,000) !";
		items[] =
		{
			{ "SmokeShell", "", 50 },
			{ "HandGrenade_Stone","Flash", "", 300 },
			{ "MiniGrenade", "", 300 },
			{ "hgun_ACPC2_F", "", 1000 },
			{ "hgun_Pistol_heavy_01_F", "", 1250 },
			{ "hgun_Pistol_heavy_02_F", "", 2500 },
			{ "hgun_Rook40_F", "", 2500 },
			{ "hgun_P07_F", "", 2500 },
			{ "hgun_PDW2000_F", "", 3500 },
			{ "SMG_01_F", "", 4500 },
			{ "SMG_02_F", "", 6000 },
			{ "arifle_SDAR_F", "", 6000 },
			{ "arifle_TRG20_F", "", 7500 },
			{ "arifle_TRG21_F", "", 8000 },
			{ "arifle_TRG21_GL_F", "", 9500 },
			{ "arifle_Mk20C_F", "", 8000 },
			{ "arifle_Mk20_F", "", 8500 },
			{ "arifle_Mk20_GL_F", "", 10000 },
			{ "arifle_Katiba_C_F", "", 14000 },
			{ "arifle_Katiba_F", "", 16500 },
			{ "arifle_MXC_F", "", 14000 },
			{ "arifle_MX_F", "", 15000 },
			{ "arifle_MXM_F", "", 16500 },
			{ "arifle_MX_SW_F", "", 22500 },
			{ "LMG_Mk200_F", "", 37500 },
			{ "srifle_EBR_F", "", 42500 },
			{ "srifle_LRR_F", "", 65000 },
			{ "optic_Aco", "", 250 },
			{ "optic_Holosight", "", 300 },
			{ "optic_Arco", "", 450 },
			{ "optic_SOS", "", 1000 },
			{ "acc_flashlight", "", 200 },
			{ "acc_pointer_IR", "", 250 },
			{ "9Rnd_45ACP_Mag", "", 100 },
			{ "11Rnd_45ACP_Mag", "", 125 },
			{ "6Rnd_45ACP_Cylinder", "", 125 },
			{ "30Rnd_45ACP_Mag_SMG_01", "", 175 },
			{ "16Rnd_9x21_Mag", "", 250 },
			{ "30Rnd_9x21_Mag", "", 500 },
			{ "20Rnd_556x45_UW_mag", "", 400 },
			{ "30Rnd_556x45_Stanag", "", 600 },
			{ "30Rnd_65x39_caseless_mag", "", 750 },
			{ "100Rnd_65x39_caseless_mag", "", 2700 },
			{ "1Rnd_HE_Grenade_shell", "", 50 },
			{ "UGL_FlareWhite_F", "", 50 },
			{ "1Rnd_Smoke_Grenade_shell", "", 50 },
			{ "200Rnd_65x39_cased_Box", "", 2750 },
			{ "20Rnd_762x51_Mag", "", 2000 },
			{ "7Rnd_408_Mag", "", 1500 }
		};
	};
	class premW
	{
		name = "Armurerie Rebelle *premium";
		side = "civ";
		license = "premW";
		level = -1;
		msg = "Vous n'avez pas la licence Premium Weapon !";
		items[] =
		{
			{ "SmokeShell", "", 50 },
			{ "HandGrenade_Stone","Flash", "", 300 },
			{ "MiniGrenade", "", 300 },
			{ "HandGrenade", "", 500 },
			{ "ClaymoreDirectionalMine_Remote_Mag", "", 1500 },
			{ "APERSTripMine_Wire_Mag", "", 1500 },
			{ "APERSMine_Range_Mag", "", 1500 },
			{ "APERSBoundingMine_Range_Mag", "", 2500 },
			{ "SLAMDirectionalMine_Wire_Mag", "", 5000 },
			{ "ATMine_Range_Mag", "", 7500 },
			{ "DemoCharge_Remote_Mag", "", 12500 },
			{ "SatchelCharge_Remote_Mag", "", 27500 },
			{ "hgun_ACPC2_F", "", 1000 },
			{ "hgun_Pistol_heavy_01_F", "", 1250 },
			{ "hgun_Pistol_heavy_02_F", "", 2500 },
			{ "hgun_Rook40_F", "", 2500 },
			{ "hgun_P07_F", "", 2500 },
			{ "hgun_PDW2000_F", "", 3500 },
			{ "SMG_01_F", "", 4500 },
			{ "SMG_02_F", "", 6000 },
			{ "arifle_SDAR_F", "", 6000 },
			{ "arifle_TRG20_F", "", 7500 },
			{ "arifle_TRG21_F", "", 8000 },
			{ "arifle_TRG21_GL_F", "", 9500 },
			{ "arifle_Mk20C_F", "", 8000 },
			{ "arifle_Mk20_F", "", 8500 },
			{ "arifle_Mk20_GL_F", "", 10000 },
			{ "arifle_Katiba_C_F", "", 14000 },
			{ "arifle_Katiba_F", "", 16500 },
			{ "arifle_Katiba_GL_F", "", 18000 },
			{ "arifle_MXC_F", "", 14000 },
			{ "arifle_MXC_Black_F", "", 14500 },
			{ "arifle_MX_F", "", 15000 },
			{ "arifle_MX_Black_F", "", 15000 },
			{ "arifle_MX_GL_F", "", 16500 },
			{ "arifle_MX_GL_Black_F", "", 17000 },
			{ "arifle_MXM_F", "", 16500 },
			{ "arifle_MXM_Black_F", "", 18000 },
			{ "arifle_MX_SW_F", "", 22500 },
			{ "arifle_MX_SW_Black_F", "", 23000 },
			{ "LMG_Mk200_F", "", 37500 },
			{ "LMG_Zafir_F", "", 52500 },
			{ "srifle_EBR_F", "", 42500 },
			{ "srifle_DMR_01_F", "", 38500 },
			{ "srifle_GM6_F", "", 85000 },
			{ "srifle_GM6_camo_F", "", 90000 },
			{ "srifle_LRR_F", "", 65000 },
			{ "srifle_LRR_camo_F", "", 70000 },
			{ "optic_MRD", "", 150 },
			{ "optic_Yorris", "", 200 },
			{ "optic_Aco", "", 250 },
			{ "optic_Holosight", "", 300 },
			{ "optic_Arco", "", 450 },
			{ "optic_Hamr", "", 600 },
			{ "optic_MRCO", "", 800 },
			{ "optic_SOS", "", 1000 },
			{ "optic_DMS", "", 1250 },
			{ "optic_LRPS", "", 1750 },
			{ "optic_NVS", "", 2500 },
			{ "optic_AMS", "", 3800 },
			{ "optic_AMS_khk", "", 1800 },
			{ "optic_AMS_snd", "", 1800 },
			{ "optic_KHS_blk", "", 2100 },
			{ "optic_KHS_hex", "", 2100 },
			{ "optic_KHS_old", "", 2100 },
			{ "optic_KHS_tan", "", 2100 },
			{ "bipod_01_F_snd", "", 500 },
			{ "bipod_01_F_blk", "", 500 },
			{ "bipod_01_F_mtp", "", 500 },
			{ "bipod_02_F_blk", "", 500 },
			{ "bipod_02_F_tan", "", 500 },
			{ "bipod_02_F_hex", "", 500 },
			{ "bipod_03_F_blk", "", 500 },
			{ "bipod_03_F_oli", "", 500 },
			{ "muzzle_snds_L", "", 250 },
			{ "muzzle_snds_M", "", 500 },
			{ "muzzle_snds_H", "", 750 },
			{ "muzzle_snds_H_MG", "", 1000 },
			{ "muzzle_snds_B", "", 1250 },
			{ "acc_flashlight", "", 200 },
			{ "acc_pointer_IR", "", 250 },
			{ "9Rnd_45ACP_Mag", "", 100 },
			{ "11Rnd_45ACP_Mag", "", 125 },
			{ "6Rnd_45ACP_Cylinder", "", 125 },
			{ "30Rnd_45ACP_Mag_SMG_01", "", 175 },
			{ "30Rnd_45ACP_Mag_SMG_01_tracer_green", "", 225 },
			{ "16Rnd_9x21_Mag", "", 250 },
			{ "30Rnd_9x21_Mag", "", 500 },
			{ "20Rnd_556x45_UW_mag", "", 400 },
			{ "30Rnd_556x45_Stanag", "", 600 },
			{ "30Rnd_556x45_Stanag_Tracer_Red", "", 700 },
			{ "30Rnd_556x45_Stanag_Tracer_Green", "", 700 },
			{ "30Rnd_556x45_Stanag_Tracer_Yellow", "", 700 },
			{ "30Rnd_65x39_caseless_green", "", 750 },
			{ "30Rnd_65x39_caseless_green_mag_Tracer", "", 850 },
			{ "30Rnd_65x39_caseless_mag", "", 750 },
			{ "100Rnd_65x39_caseless_mag", "", 2700 },
			{ "1Rnd_HE_Grenade_shell", "", 50 },
			{ "3Rnd_HE_Grenade_shell", "", 150 },
			{ "UGL_FlareWhite_F", "", 50 },
			{ "3Rnd_UGL_FlareWhite_F", "", 150 },
			{ "1Rnd_Smoke_Grenade_shell", "", 50 },
			{ "3Rnd_Smoke_Grenade_shell", "", 150 },
			{ "200Rnd_65x39_cased_Box", "", 2750 },
			{ "200Rnd_65x39_cased_Box_Tracer", "", 3000 },
			{ "150Rnd_762x54_Box", "", 3750 },
			{ "150Rnd_762x54_Box_Tracer", "", 4000 },
			{ "10Rnd_762x54_Mag", "", 1000 },
			{ "20Rnd_762x51_Mag", "", 2000 },
			{ "5Rnd_127x108_Mag", "", 15000 },
			{ "5Rnd_127x108_APDS_Mag", "", 35000 },
			{ "7Rnd_408_Mag", "", 1500 }
		};
	};
	class reb_wpdlc_nonpremium
	{
		name = "Marksmen DLC";
		side = "civ";
		license = "";
		level = -1;
		msg = "";
		items[] =
		{
			{ "srifle_DMR_02_camo_F", "", 47500 },
			{ "MMG_02_camo_F", "", 75000 },
			{ "srifle_DMR_03_multicam_F", "", 47500 },
			{ "srifle_DMR_06_camo_F", "", 34500 },
			{ "optic_AMS", "", 3800 },
			{ "optic_KHS_blk", "", 2100 },
			{ "optic_NVS", "", 2500 },
			{ "bipod_01_F_blk", "", 500 },
			{ "bipod_02_F_blk", "", 500 },
			{ "bipod_03_F_blk", "", 500 },
			{ "acc_flashlight", "", 200 },
			{ "acc_pointer_IR", "", 250 },
			{ "10Rnd_338_Mag", "", 12500 },
			{ "130Rnd_338_Mag", "", 35000 },
			{ "20Rnd_762x51_Mag", "", 2000 }
		};
	};
	class reb_wpdlc
	{
		name = "Marksmen DLC *premium";
		side = "civ";
		license = "premW";
		level = -1;
		msg = "";
		items[] =
		{
			{ "srifle_DMR_02_F", "", 47500 },
			{ "srifle_DMR_02_camo_F", "", 47500 },
			{ "srifle_DMR_02_sniper_F", "", 47500 },
			{ "MMG_02_black_F", "", 75000 },
			{ "MMG_02_camo_F", "", 75000 },
			{ "MMG_02_sand_F", "", 75000 },
			{ "srifle_DMR_03_F", "", 47500 },
			{ "srifle_DMR_03_khaki_F", "", 47500 },
			{ "srifle_DMR_03_multicam_F", "", 47500 },
			{ "srifle_DMR_03_tan_F", "", 47500 },
			{ "srifle_DMR_03_woodland_F", "", 47500 },
			{ "srifle_DMR_06_camo_F", "", 34500 },
			{ "srifle_DMR_06_olive_F", "", 34500 },
			{ "srifle_DMR_05_blk_F", "", 98500 },
			{ "srifle_DMR_05_hex_F", "", 98500 },
			{ "srifle_DMR_05_tan_F", "", 98500 },
			{ "MMG_01_hex_F", "", 175000 },
			{ "MMG_01_tan_F", "", 175000 },
			{ "srifle_DMR_04_F", "", 44500 },
			{ "srifle_DMR_04_Tan_F", "", 44500 },
			{ "muzzle_snds_338_black", "", 1000 },
			{ "muzzle_snds_338_green", "", 1000 },
			{ "muzzle_snds_338_sand", "", 1000 },
			{ "muzzle_snds_B", "", 1250 },
			{ "muzzle_snds_93mmg", "", 4750 },
			{ "muzzle_snds_93mmg_tan", "", 4750 },
			{ "optic_AMS", "", 3800 },
			{ "optic_AMS_khk", "", 1800 },
			{ "optic_AMS_snd", "", 1800 },
			{ "optic_KHS_blk", "", 2100 },
			{ "optic_KHS_hex", "", 2100 },
			{ "optic_KHS_old", "", 2100 },
			{ "optic_KHS_tan", "", 2100 },
			{ "optic_NVS", "", 2500 },
			{ "bipod_01_F_snd", "", 500 },
			{ "bipod_01_F_blk", "", 500 },
			{ "bipod_01_F_mtp", "", 500 },
			{ "bipod_02_F_blk", "", 500 },
			{ "bipod_02_F_tan", "", 500 },
			{ "bipod_02_F_hex", "", 500 },
			{ "bipod_03_F_blk", "", 500 },
			{ "bipod_03_F_oli", "", 500 },
			{ "acc_flashlight", "", 200 },
			{ "acc_pointer_IR", "", 250 },
			{ "10Rnd_338_Mag", "", 12500 },
			{ "130Rnd_338_Mag", "", 35000 },
			{ "20Rnd_762x51_Mag", "", 2000 },
			{ "10Rnd_93x64_DMR_05_Mag", "", 17500 },
			{ "150Rnd_93x64_Mag", "", 42500 },
			{ "10Rnd_127x54_Mag", "", 7500 }
		};
	};
	//GENSTORE
	class genstore
	{
		name = "Magasin Général";
		side = "civ";
		license = "";
		level = -1;
		msg = "";
		items[] =
		{
			{ "ItemMap", "", 5 },
			{ "ItemCompass", "", 25 },
			{ "ItemGPS", "", 280 },
			{ "NVGoggles", "", 120 },
			{ "NVGoggles_OPFOR", "", 120 },
			{ "NVGoggles_INDEP", "", 120 },
		//	{ "Laserbatteries", "", 0 },
		//	{ "Laserdesignator", "", 0 },
		//	{ "Laserdesignator_02", "", 0 },
		//	{ "Laserdesignator_03", "", 0 },
			{ "Binocular", "", 300 },
			{ "Rangefinder", "", 420 },
			{ "MineDetector", "", 4200 },
			{ "FirstAidKit", "", 250 },
			{ "Medikit", "", 29500 },
			{ "ToolKit", "", 12500 },
			{ "hgun_Pistol_Signal_F", "", 130 },
			{ "6Rnd_GreenSignal_F", "", 10 },
			{ "6Rnd_RedSignal_F", "", 10 },
			{ "Chemlight_red", "", 1 },
			{ "Chemlight_yellow", "", 1 },
			{ "Chemlight_green", "", 1 },
			{ "Chemlight_blue", "", 1 }
		};
	};
	class genstoreReb
	{
		name = "Magasin Général Rebelle";
		side = "civ";
		license = "rebel";
		level = -1;
		msg = "";
		items[] =
		{
			{ "ItemMap", "", 5 },
			{ "ItemCompass", "", 25 },
			{ "ItemGPS", "", 280 },
			{ "NVGoggles", "", 120 },
			{ "NVGoggles_OPFOR", "", 120 },
			{ "NVGoggles_INDEP", "", 120 },
		//	{ "Laserbatteries", "", 0 },
		//	{ "Laserdesignator", "", 0 },
		//	{ "Laserdesignator_02", "", 0 },
		//	{ "Laserdesignator_03", "", 0 },
			{ "Binocular", "", 210 },
			{ "Rangefinder", "", 340 },
			{ "MineDetector", "", 2700 },
			{ "FirstAidKit", "", 250 },
			{ "Medikit", "", 19500 },
			{ "ToolKit", "", 5750 },			
			{ "hgun_Pistol_Signal_F", "", 130 },
			{ "6Rnd_GreenSignal_F", "", 10 },
			{ "6Rnd_RedSignal_F", "", 10 },
			{ "Chemlight_red", "", 1 },
			{ "Chemlight_yellow", "", 1 },
			{ "Chemlight_green", "", 1 },
			{ "Chemlight_blue", "", 1 }
		};
	};
	class genstoreCop
	{
		name = "Magasin Général F.A.";
		side = "cop";
		license = "";
		level = 1;
		msg = "";
		items[] =
		{
			{ "ItemMap", "", 5 },
			{ "ItemCompass", "", 25 },
			{ "ItemGPS", "", 280 },
			{ "NVGoggles", "", 120 },
			{ "NVGoggles_OPFOR", "", 120 },
			{ "NVGoggles_INDEP", "", 120 },
		//	{ "Laserdesignator", "", 0 },
		//	{ "Laserdesignator_02", "", 0 },
		//	{ "Laserdesignator_03", "", 0 },
			{ "Binocular", "", 210 },
			{ "Rangefinder", "", 340 },
			{ "MineDetector", "", 4200 },
			{ "B_UavTerminal", "", 4700 },
			{ "FirstAidKit", "", 250 },
			{ "Medikit", "", 25000 },
			{ "ToolKit", "", 15000 },
			{ "hgun_Pistol_Signal_F", "", 130 },
			{ "6Rnd_GreenSignal_F", "", 10 },
			{ "6Rnd_RedSignal_F", "", 10 },
			{ "Chemlight_red", "", 1 },
			{ "Chemlight_yellow", "", 1 },
			{ "Chemlight_green", "", 1 },
			{ "Chemlight_blue", "", 1 }
		};
	};
	//COP
	class 1_2
	{
		name = "Armurerie Level 1-2";
		side = "cop";
		license = "";
		level = 1;
		msg = "Vous n'avez pas le level requis.";
		items[] =
		{
			{ "SmokeShell", "", 0 },
			{ "HandGrenade_Stone","Flash", "", 0 },
			{ "MiniGrenade", "", 0 },
		//	{ "HandGrenade", "", 0 },
		//	{ "B_IR_Grenade", "", 0 },
		//	{ "O_IR_Grenade", "", 0 },
		//	{ "I_IR_Grenade", "", 0 },
		//	{ "ClaymoreDirectionalMine_Remote_Mag", "", 0 },
		//	{ "APERSTripMine_Wire_Mag", "", 0 },
		//	{ "APERSMine_Range_Mag", "", 0 },
		//	{ "APERSBoundingMine_Range_Mag", "", 0 },
		//	{ "SLAMDirectionalMine_Wire_Mag", "", 0 },
		//	{ "ATMine_Range_Mag", "", 0 },
		//	{ "DemoCharge_Remote_Mag", "", 0 },
		//	{ "SatchelCharge_Remote_Mag", "", 0 },
			{ "hgun_ACPC2_F", "", 0 },
			{ "hgun_Pistol_heavy_01_F", "", 0 },
			{ "hgun_Pistol_heavy_02_F", "", 0 },
			{ "hgun_Rook40_F", "", 0 },
			{ "hgun_P07_F", "", 0 },
			{ "hgun_PDW2000_F", "", 0 },
			{ "SMG_01_F", "", 0 },
			{ "SMG_02_F", "", 0 },
			{ "arifle_SDAR_F", "", 0 },
			{ "arifle_TRG20_F", "", 0 },
			{ "arifle_TRG21_F", "", 0 },
			{ "arifle_TRG21_GL_F", "", 0 },
			{ "arifle_Mk20C_F", "", 0 },
			{ "arifle_Mk20_F", "", 0 },
			{ "arifle_Mk20_GL_F", "", 0 },
			{ "arifle_Katiba_C_F", "", 0 },
			{ "arifle_Katiba_F", "", 0 },
			{ "arifle_Katiba_GL_F", "", 0 },
			{ "arifle_MXC_F", "", 0 },
			{ "arifle_MXC_Black_F", "", 0 },
			{ "arifle_MX_SW_F", "", 0 },
			{ "arifle_MX_SW_Black_F", "", 0 },
			{ "arifle_MX_F", "", 0 },
			{ "arifle_MX_Black_F", "", 0 },
			{ "arifle_MX_GL_F", "", 0 },
			{ "arifle_MX_GL_Black_F", "", 0 },
			{ "arifle_MXM_F", "", 0 },
			{ "arifle_MXM_Black_F", "", 0 },
			{ "LMG_Mk200_F", "", 0 },
		//	{ "LMG_Zafir_F", "", 0 },
		//	{ "srifle_EBR_F", "", 0 },
		//	{ "srifle_DMR_01_F", "", 0 },
		//	{ "srifle_GM6_F", "", 0 },
		//	{ "srifle_GM6_camo_F", "", 0 },
		//	{ "srifle_LRR_F", "", 0 },
		//	{ "srifle_LRR_camo_F", "", 0 },
		//	{ "launch_RPG32_F", "", 0 },
		//	{ "launch_Titan_F", "", 0 },
		//	{ "launch_Titan_short_F", "", 0 },
		//	{ "launch_NLAW_F", "", 0 },
			{ "optic_MRD", "", 0 },
			{ "optic_Yorris", "", 0 },
			{ "optic_Aco", "", 0 },
			{ "optic_Holosight", "", 0 },
			{ "optic_Arco", "", 0 },
			{ "optic_Hamr", "", 0 },
			{ "optic_MRCO", "", 0 },
		//	{ "optic_SOS", "", 0 },
		//	{ "optic_DMS", "", 0 },
		//	{ "optic_LRPS", "", 0 },
			{ "optic_NVS", "", 0 },
		//	{ "optic_Nightstalker", "", 0 },
		//	{ "optic_tws", "", 0 },
		//	{ "optic_tws_mg", "", 0 },
		//	{ "optic_AMS", "", 0 },
		//	{ "optic_AMS_khk", "", 0 },
		//	{ "optic_AMS_snd", "", 0 },
		//	{ "optic_KHS_blk", "", 0 },
		//	{ "optic_KHS_hex", "", 0 },
		//	{ "optic_KHS_old", "", 0 },
		//	{ "optic_KHS_tan", "", 0 },
			{ "bipod_01_F_snd", "", 0 },
			{ "bipod_01_F_blk", "", 0 },
			{ "bipod_01_F_mtp", "", 0 },
			{ "bipod_02_F_blk", "", 0 },
			{ "bipod_02_F_tan", "", 0 },
			{ "bipod_02_F_hex", "", 0 },
			{ "bipod_03_F_blk", "", 0 },
			{ "bipod_03_F_oli", "", 0 },
		//	{ "muzzle_snds_L", "", 0 },				//9mm
		//	{ "muzzle_snds_M", "", 0 },				//5,56 mm
		//	{ "muzzle_snds_H", "", 0 },				//6,5 mm
		//	{ "muzzle_snds_H_MG", "", 0 },			//6,5 mm (mk200)
		//	{ "muzzle_snds_B", "", 0 },				//7,62 mm
			{ "acc_flashlight", "", 0 },
			{ "acc_pointer_IR", "", 0 },
			{ "9Rnd_45ACP_Mag", "", 0 },
			{ "11Rnd_45ACP_Mag", "", 0 },
			{ "6Rnd_45ACP_Cylinder", "", 0 },
			{ "30Rnd_45ACP_Mag_SMG_01", "", 0 },
			{ "30Rnd_45ACP_Mag_SMG_01_tracer_green", "", 0 },
			{ "16Rnd_9x21_Mag", "", 0 },
			{ "30Rnd_9x21_Mag", "", 0 },
			{ "20Rnd_556x45_UW_mag", "", 0 },
			{ "30Rnd_556x45_Stanag", "", 0 },
			{ "30Rnd_556x45_Stanag_Tracer_Red", "", 0 },
			{ "30Rnd_556x45_Stanag_Tracer_Green", "", 0 },
			{ "30Rnd_556x45_Stanag_Tracer_Yellow", "", 0 },
			{ "30Rnd_65x39_caseless_green", "", 0 },
			{ "30Rnd_65x39_caseless_green_mag_Tracer", "", 0 },
			{ "30Rnd_65x39_caseless_mag", "", 0 },
			{ "30Rnd_65x39_caseless_mag_Tracer", "", 0 },
			{ "100Rnd_65x39_caseless_mag", "", 0 },
		//	{ "1Rnd_HE_Grenade_shell", "", 0 },
		//	{ "3Rnd_HE_Grenade_shell", "", 0 },
			{ "UGL_FlareWhite_F", "", 0 },
			{ "UGL_FlareGreen_F", "", 0 },
			{ "UGL_FlareRed_F", "", 0 },
			{ "UGL_FlareYellow_F", "", 0 },
		//	{ "UGL_FlareCIR_F", "", 0 },
			{ "3Rnd_UGL_FlareWhite_F", "", 0 },
			{ "3Rnd_UGL_FlareGreen_F", "", 0 },
			{ "3Rnd_UGL_FlareRed_F", "", 0 },
			{ "3Rnd_UGL_FlareYellow_F", "", 0 },
		//	{ "3Rnd_UGL_FlareCIR_F", "", 0 },
			{ "1Rnd_Smoke_Grenade_shell", "", 0 },
			{ "1Rnd_SmokeRed_Grenade_shell", "", 0 },
			{ "1Rnd_SmokeGreen_Grenade_shell", "", 0 },
			{ "1Rnd_SmokeYellow_Grenade_shell", "", 0 },
			{ "1Rnd_SmokePurple_Grenade_shell", "", 0 },
			{ "1Rnd_SmokeBlue_Grenade_shell", "", 0 },
			{ "1Rnd_SmokeOrange_Grenade_shell", "", 0 },
			{ "3Rnd_Smoke_Grenade_shell", "", 0 },
			{ "3Rnd_SmokeRed_Grenade_shell", "", 0 },
			{ "3Rnd_SmokeGreen_Grenade_shell", "", 0 },
			{ "3Rnd_SmokeYellow_Grenade_shell", "", 0 },
			{ "3Rnd_SmokePurple_Grenade_shell", "", 0 },
			{ "3Rnd_SmokeBlue_Grenade_shell", "", 0 },
			{ "3Rnd_SmokeOrange_Grenade_shell", "", 0 },
			{ "200Rnd_65x39_cased_Box", "", 0 },
			{ "200Rnd_65x39_cased_Box_Tracer", "", 0 }
		//	{ "150Rnd_762x54_Box", "", 0 },
		//	{ "150Rnd_762x54_Box_Tracer", "", 0 },
		//	{ "10Rnd_762x54_Mag", "", 0 },
		//	{ "20Rnd_762x51_Mag", "", 0 },
		//	{ "5Rnd_127x108_Mag", "", 0 },
		//	{ "5Rnd_127x108_APDS_Mag", "", 0 },
		//	{ "7Rnd_408_Mag", "", 0 },
		//	{ "RPG32_F", "", 0 },
		//	{ "RPG32_HE_F", "", 0 },
		//	{ "Titan_AP", "", 0 },
		//	{ "Titan_AT", "", 0 },
		//	{ "Titan_AA", "", 0 },
		//	{ "NLAW_F", "", 0 },
		};
	};
	class 3_6
	{
		name = "Armurerie Level 3-6";
		side = "cop";
		license = "";
		level = 3;
		msg = "Vous n'êtes pas level 11 !";
		items[] =
		{
			{ "SmokeShell", "", 0 },
			{ "HandGrenade_Stone","Flash", "", 0 },
			{ "MiniGrenade", "", 0 },
		//	{ "HandGrenade", "", 0 },
		//	{ "B_IR_Grenade", "", 0 },
		//	{ "O_IR_Grenade", "", 0 },
		//	{ "I_IR_Grenade", "", 0 },
		//	{ "ClaymoreDirectionalMine_Remote_Mag", "", 0 },
		//	{ "APERSTripMine_Wire_Mag", "", 0 },
		//	{ "APERSMine_Range_Mag", "", 0 },
		//	{ "APERSBoundingMine_Range_Mag", "", 0 },
		//	{ "SLAMDirectionalMine_Wire_Mag", "", 0 },
		//	{ "ATMine_Range_Mag", "", 0 },
		//	{ "DemoCharge_Remote_Mag", "", 0 },
			{ "SatchelCharge_Remote_Mag", "", 0 },
		//	{ "hgun_ACPC2_F", "", 0 },
		//	{ "hgun_Pistol_heavy_01_F", "", 0 },
		//	{ "hgun_Pistol_heavy_02_F", "", 0 },
		//	{ "hgun_Rook40_F", "", 0 },
		//	{ "hgun_P07_F", "", 0 },
		//	{ "hgun_PDW2000_F", "", 0 },
		//	{ "SMG_01_F", "", 0 },
		//	{ "SMG_02_F", "", 0 },
		//	{ "arifle_SDAR_F", "", 0 },
		//	{ "arifle_TRG20_F", "", 0 },
		//	{ "arifle_TRG21_F", "", 0 },
		//	{ "arifle_TRG21_GL_F", "", 0 },
		//	{ "arifle_Mk20C_F", "", 0 },
		//	{ "arifle_Mk20_F", "", 0 },
		//	{ "arifle_Mk20_GL_F", "", 0 },
		//	{ "arifle_Katiba_C_F", "", 0 },
		//	{ "arifle_Katiba_F", "", 0 },
		//	{ "arifle_Katiba_GL_F", "", 0 },
		//	{ "arifle_MXC_F", "", 0 },
		//	{ "arifle_MXC_Black_F", "", 0 },
		//	{ "arifle_MX_SW_F", "", 0 },
		//	{ "arifle_MX_SW_Black_F", "", 0 },
		//	{ "arifle_MX_F", "", 0 },
		//	{ "arifle_MX_Black_F", "", 0 },
		//	{ "arifle_MX_GL_F", "", 0 },
		//	{ "arifle_MX_GL_Black_F", "", 0 },
		//	{ "arifle_MXM_F", "", 0 },
		//	{ "arifle_MXM_Black_F", "", 0 },
		//	{ "LMG_Mk200_F", "", 0 },
			{ "LMG_Zafir_F", "", 0 },
			{ "srifle_EBR_F", "", 0 },
			{ "srifle_DMR_01_F", "", 0 },
		//	{ "srifle_GM6_F", "", 0 },
		//	{ "srifle_GM6_camo_F", "", 0 },
			{ "srifle_LRR_F", "", 0 },
			{ "srifle_LRR_camo_F", "", 0 },
		//	{ "launch_RPG32_F", "", 0 },
		//	{ "launch_Titan_F", "", 0 },
		//	{ "launch_Titan_short_F", "", 0 },
		//	{ "launch_NLAW_F", "", 0 },
			{ "optic_MRD", "", 0 },
			{ "optic_Yorris", "", 0 },
			{ "optic_Aco", "", 0 },
			{ "optic_Holosight", "", 0 },
			{ "optic_Arco", "", 0 },
			{ "optic_Hamr", "", 0 },
			{ "optic_MRCO", "", 0 },
			{ "optic_SOS", "", 0 },
			{ "optic_DMS", "", 0 },
			{ "optic_LRPS", "", 0 },
			{ "optic_NVS", "", 0 },
		//	{ "optic_Nightstalker", "", 0 },
		//	{ "optic_tws", "", 0 },
		//	{ "optic_tws_mg", "", 0 },
			{ "optic_AMS", "", 0 },
			{ "optic_AMS_khk", "", 0 },
			{ "optic_AMS_snd", "", 0 },
			{ "optic_KHS_blk", "", 0 },
			{ "optic_KHS_hex", "", 0 },
			{ "optic_KHS_old", "", 0 },
			{ "optic_KHS_tan", "", 0 },
			{ "bipod_01_F_snd", "", 0 },
			{ "bipod_01_F_blk", "", 0 },
			{ "bipod_01_F_mtp", "", 0 },
			{ "bipod_02_F_blk", "", 0 },
			{ "bipod_02_F_tan", "", 0 },
			{ "bipod_02_F_hex", "", 0 },
			{ "bipod_03_F_blk", "", 0 },
			{ "bipod_03_F_oli", "", 0 },
			{ "muzzle_snds_L", "", 0 },				//9mm
			{ "muzzle_snds_M", "", 0 },				//5,56 mm
			{ "muzzle_snds_H", "", 0 },				//6,5 mm
			{ "muzzle_snds_H_MG", "", 0 },			//6,5 mm (mk200)
			{ "muzzle_snds_B", "", 0 },				//7,62 mm
			{ "acc_flashlight", "", 0 },
			{ "acc_pointer_IR", "", 0 },
		//	{ "9Rnd_45ACP_Mag", "", 0 },
		//	{ "11Rnd_45ACP_Mag", "", 0 },
		//	{ "6Rnd_45ACP_Cylinder", "", 0 },
		//	{ "30Rnd_45ACP_Mag_SMG_01", "", 0 },
		//	{ "30Rnd_45ACP_Mag_SMG_01_tracer_green", "", 0 },
		//	{ "16Rnd_9x21_Mag", "", 0 },
		//	{ "30Rnd_9x21_Mag", "", 0 },
		//	{ "20Rnd_556x45_UW_mag", "", 0 },
		//	{ "30Rnd_556x45_Stanag", "", 0 },
		//	{ "30Rnd_556x45_Stanag_Tracer_Red", "", 0 },
		//	{ "30Rnd_556x45_Stanag_Tracer_Green", "", 0 },
		//	{ "30Rnd_556x45_Stanag_Tracer_Yellow", "", 0 },
		//	{ "30Rnd_65x39_caseless_green", "", 0 },
		//	{ "30Rnd_65x39_caseless_green_mag_Tracer", "", 0 },
		//	{ "30Rnd_65x39_caseless_mag", "", 0 },
		//	{ "30Rnd_65x39_caseless_mag_Tracer", "", 0 },
		//	{ "100Rnd_65x39_caseless_mag", "", 0 },
			{ "1Rnd_HE_Grenade_shell", "", 0 },
			{ "3Rnd_HE_Grenade_shell", "", 0 },
		//	{ "UGL_FlareWhite_F", "", 0 },
		//	{ "UGL_FlareGreen_F", "", 0 },
		//	{ "UGL_FlareRed_F", "", 0 },
		//	{ "UGL_FlareYellow_F", "", 0 },
		//	{ "UGL_FlareCIR_F", "", 0 },
		//	{ "3Rnd_UGL_FlareWhite_F", "", 0 },
		//	{ "3Rnd_UGL_FlareGreen_F", "", 0 },
		//	{ "3Rnd_UGL_FlareRed_F", "", 0 },
		//	{ "3Rnd_UGL_FlareYellow_F", "", 0 },
		//	{ "3Rnd_UGL_FlareCIR_F", "", 0 },
		//	{ "1Rnd_Smoke_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeRed_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeGreen_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeYellow_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokePurple_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeBlue_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeOrange_Grenade_shell", "", 0 },
		//	{ "3Rnd_Smoke_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeRed_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeGreen_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeYellow_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokePurple_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeBlue_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeOrange_Grenade_shell", "", 0 },
		//	{ "200Rnd_65x39_cased_Box", "", 0 },
		//	{ "200Rnd_65x39_cased_Box_Tracer", "", 0 },
			{ "150Rnd_762x54_Box", "", 0 },
			{ "150Rnd_762x54_Box_Tracer", "", 0 },
			{ "10Rnd_762x54_Mag", "", 0 },
			{ "20Rnd_762x51_Mag", "", 0 },
		//	{ "5Rnd_127x108_Mag", "", 0 },
		//	{ "5Rnd_127x108_APDS_Mag", "", 0 },
			{ "7Rnd_408_Mag", "", 0 }
		//	{ "RPG32_F", "", 0 },
		//	{ "RPG32_HE_F", "", 0 },
		//	{ "Titan_AP", "", 0 },
		//	{ "Titan_AT", "", 0 },
		//	{ "Titan_AA", "", 0 },
		//	{ "NLAW_F", "", 0 },
		};
	};
	class 7_14
	{
		name = "Armurerie Level 7-14 ";
		side = "cop";
		license = "";
		level = 7;
		msg = "Vous n'avez pas le level requis.";
		items[] =
		{
			{ "SmokeShell", "", 0 },
			{ "HandGrenade_Stone","Flash", "", 0 },
			{ "MiniGrenade", "", 0 },
			{ "HandGrenade", "", 0 },
			{ "B_IR_Grenade", "", 0 },
			{ "O_IR_Grenade", "", 0 },
			{ "I_IR_Grenade", "", 0 },
			{ "ClaymoreDirectionalMine_Remote_Mag", "", 0 },
			{ "APERSTripMine_Wire_Mag", "", 0 },
			{ "APERSMine_Range_Mag", "", 0 },
			{ "APERSBoundingMine_Range_Mag", "", 0 },
			{ "SLAMDirectionalMine_Wire_Mag", "", 0 },
			{ "ATMine_Range_Mag", "", 0 },
			{ "DemoCharge_Remote_Mag", "", 0 },
			{ "SatchelCharge_Remote_Mag", "", 0 },
			{ "hgun_ACPC2_F", "", 0 },
		//	{ "hgun_Pistol_heavy_01_F", "", 0 },
		//	{ "hgun_Pistol_heavy_02_F", "", 0 },
		//	{ "hgun_Rook40_F", "", 0 },
		//	{ "hgun_P07_F", "", 0 },
		//	{ "hgun_PDW2000_F", "", 0 },
		//	{ "SMG_01_F", "", 0 },
		//	{ "SMG_02_F", "", 0 },
		//	{ "arifle_SDAR_F", "", 0 },
		//	{ "arifle_TRG20_F", "", 0 },
		//	{ "arifle_TRG21_F", "", 0 },
		//	{ "arifle_TRG21_GL_F", "", 0 },
		//	{ "arifle_Mk20C_F", "", 0 },
		//	{ "arifle_Mk20_F", "", 0 },
		//	{ "arifle_Mk20_GL_F", "", 0 },
		//	{ "arifle_Katiba_C_F", "", 0 },
		//	{ "arifle_Katiba_F", "", 0 },
		//	{ "arifle_Katiba_GL_F", "", 0 },
		//	{ "arifle_MXC_F", "", 0 },
		//	{ "arifle_MXC_Black_F", "", 0 },
		//	{ "arifle_MX_SW_F", "", 0 },
		//	{ "arifle_MX_SW_Black_F", "", 0 },
		//	{ "arifle_MX_F", "", 0 },
		//	{ "arifle_MX_Black_F", "", 0 },
		//	{ "arifle_MX_GL_F", "", 0 },
		//	{ "arifle_MX_GL_Black_F", "", 0 },
		//	{ "arifle_MXM_F", "", 0 },
		//	{ "arifle_MXM_Black_F", "", 0 },
		//	{ "LMG_Mk200_F", "", 0 },
		//	{ "LMG_Zafir_F", "", 0 },
		//	{ "srifle_EBR_F", "", 0 },
			{ "srifle_DMR_01_F", "", 0 },
			{ "srifle_GM6_F", "", 0 },
			{ "srifle_GM6_camo_F", "", 0 },
			{ "srifle_LRR_F", "", 0 },
			{ "srifle_LRR_camo_F", "", 0 },
		//	{ "launch_RPG32_F", "", 0 },
		//	{ "launch_Titan_F", "", 0 },
		//	{ "launch_Titan_short_F", "", 0 },
		//	{ "launch_NLAW_F", "", 0 },
			{ "optic_MRD", "", 0 },
			{ "optic_Yorris", "", 0 },
			{ "optic_Aco", "", 0 },
			{ "optic_Holosight", "", 0 },
			{ "optic_Arco", "", 0 },
			{ "optic_Hamr", "", 0 },
			{ "optic_MRCO", "", 0 },
			{ "optic_SOS", "", 0 },
			{ "optic_DMS", "", 0 },
			{ "optic_LRPS", "", 0 },
			{ "optic_NVS", "", 0 },
		//	{ "optic_Nightstalker", "", 0 },
		//	{ "optic_tws", "", 0 },
		//	{ "optic_tws_mg", "", 0 },
			{ "optic_AMS", "", 0 },
			{ "optic_AMS_khk", "", 0 },
			{ "optic_AMS_snd", "", 0 },
			{ "optic_KHS_blk", "", 0 },
			{ "optic_KHS_hex", "", 0 },
			{ "optic_KHS_old", "", 0 },
			{ "optic_KHS_tan", "", 0 },
			{ "bipod_01_F_snd", "", 0 },
			{ "bipod_01_F_blk", "", 0 },
			{ "bipod_01_F_mtp", "", 0 },
			{ "bipod_02_F_blk", "", 0 },
			{ "bipod_02_F_tan", "", 0 },
			{ "bipod_02_F_hex", "", 0 },
			{ "bipod_03_F_blk", "", 0 },
			{ "bipod_03_F_oli", "", 0 },
			{ "muzzle_snds_L", "", 0 },				//9mm
			{ "muzzle_snds_M", "", 0 },				//5,56 mm
			{ "muzzle_snds_H", "", 0 },				//6,5 mm
			{ "muzzle_snds_H_MG", "", 0 },			//6,5 mm (mk200)
			{ "muzzle_snds_B", "", 0 },				//7,62 mm
			{ "acc_flashlight", "", 0 },
			{ "acc_pointer_IR", "", 0 },
		//	{ "9Rnd_45ACP_Mag", "", 0 },
		//	{ "11Rnd_45ACP_Mag", "", 0 },
		//	{ "6Rnd_45ACP_Cylinder", "", 0 },
		//	{ "30Rnd_45ACP_Mag_SMG_01", "", 0 },
		//	{ "30Rnd_45ACP_Mag_SMG_01_tracer_green", "", 0 },
		//	{ "16Rnd_9x21_Mag", "", 0 },
		//	{ "30Rnd_9x21_Mag", "", 0 },
		//	{ "20Rnd_556x45_UW_mag", "", 0 },
		//	{ "30Rnd_556x45_Stanag", "", 0 },
		//	{ "30Rnd_556x45_Stanag_Tracer_Red", "", 0 },
		//	{ "30Rnd_556x45_Stanag_Tracer_Green", "", 0 },
		//	{ "30Rnd_556x45_Stanag_Tracer_Yellow", "", 0 },
		//	{ "30Rnd_65x39_caseless_green", "", 0 },
		//	{ "30Rnd_65x39_caseless_green_mag_Tracer", "", 0 },
		//	{ "30Rnd_65x39_caseless_mag", "", 0 },
		//	{ "30Rnd_65x39_caseless_mag_Tracer", "", 0 },
		//	{ "100Rnd_65x39_caseless_mag", "", 0 },
			{ "1Rnd_HE_Grenade_shell", "", 0 },
			{ "3Rnd_HE_Grenade_shell", "", 0 },
			{ "UGL_FlareWhite_F", "", 0 },
			{ "UGL_FlareGreen_F", "", 0 },
			{ "UGL_FlareRed_F", "", 0 },
			{ "UGL_FlareYellow_F", "", 0 },
			{ "UGL_FlareCIR_F", "", 0 },
			{ "3Rnd_UGL_FlareWhite_F", "", 0 },
			{ "3Rnd_UGL_FlareGreen_F", "", 0 },
			{ "3Rnd_UGL_FlareRed_F", "", 0 },
			{ "3Rnd_UGL_FlareYellow_F", "", 0 },
		//	{ "3Rnd_UGL_FlareCIR_F", "", 0 },
		//	{ "1Rnd_Smoke_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeRed_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeGreen_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeYellow_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokePurple_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeBlue_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeOrange_Grenade_shell", "", 0 },
		//	{ "3Rnd_Smoke_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeRed_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeGreen_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeYellow_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokePurple_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeBlue_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeOrange_Grenade_shell", "", 0 },
		//	{ "200Rnd_65x39_cased_Box", "", 0 },
		//	{ "200Rnd_65x39_cased_Box_Tracer", "", 0 },
		//	{ "150Rnd_762x54_Box", "", 0 },
		//	{ "150Rnd_762x54_Box_Tracer", "", 0 },
			{ "10Rnd_762x54_Mag", "", 0 },
			{ "20Rnd_762x51_Mag", "", 0 },
			{ "5Rnd_127x108_Mag", "", 0 },
			{ "5Rnd_127x108_APDS_Mag", "", 0 },
			{ "7Rnd_408_Mag", "", 0 }
		//	{ "RPG32_F", "", 0 },
		//	{ "RPG32_HE_F", "", 0 },
		//	{ "Titan_AP", "", 0 },
		//	{ "Titan_AT", "", 0 },
		//	{ "Titan_AA", "", 0 },
		//	{ "NLAW_F", "", 0 },
		};
	};
	class 15_32
	{
		name = "Armurerie Level 15+";
		side = "cop";
		license = "";
		level = 15;
		msg = "Vous n'avez pas le level requis.";
		items[] =
		{
			{ "SmokeShell", "", 0 },
			{ "HandGrenade_Stone","Flash", "", 0 },
		//	{ "MiniGrenade", "", 0 },
			{ "HandGrenade", "", 0 },
			{ "B_IR_Grenade", "", 0 },
			{ "O_IR_Grenade", "", 0 },
			{ "I_IR_Grenade", "", 0 },
		//	{ "ClaymoreDirectionalMine_Remote_Mag", "", 0 },
		//	{ "APERSTripMine_Wire_Mag", "", 0 },
		//	{ "APERSMine_Range_Mag", "", 0 },
			{ "APERSBoundingMine_Range_Mag", "", 0 },
			{ "SLAMDirectionalMine_Wire_Mag", "", 0 },
			{ "ATMine_Range_Mag", "", 0 },
			{ "DemoCharge_Remote_Mag", "", 0 },
			{ "SatchelCharge_Remote_Mag", "", 0 },
		//	{ "hgun_ACPC2_F", "", 0 },
		//	{ "hgun_Pistol_heavy_01_F", "", 0 },
		//	{ "hgun_Pistol_heavy_02_F", "", 0 },
		//	{ "hgun_Rook40_F", "", 0 },
		//	{ "hgun_P07_F", "", 0 },
		//	{ "hgun_PDW2000_F", "", 0 },
		//	{ "SMG_01_F", "", 0 },
		//	{ "SMG_02_F", "", 0 },
		//	{ "arifle_SDAR_F", "", 0 },
		//	{ "arifle_TRG20_F", "", 0 },
		//	{ "arifle_TRG21_F", "", 0 },
		//	{ "arifle_TRG21_GL_F", "", 0 },
		//	{ "arifle_Mk20C_F", "", 0 },
		//	{ "arifle_Mk20_F", "", 0 },
		//	{ "arifle_Mk20_GL_F", "", 0 },
		//	{ "arifle_Katiba_C_F", "", 0 },
		//	{ "arifle_Katiba_F", "", 0 },
		//	{ "arifle_Katiba_GL_F", "", 0 },
		//	{ "arifle_MXC_F", "", 0 },
		//	{ "arifle_MXC_Black_F", "", 0 },
		//	{ "arifle_MX_F", "", 0 },
		//	{ "arifle_MX_Black_F", "", 0 },
		//	{ "arifle_MX_GL_F", "", 0 },
		//	{ "arifle_MX_GL_Black_F", "", 0 },
		//	{ "arifle_MXM_F", "", 0 },
		//	{ "arifle_MXM_Black_F", "", 0 },
		//	{ "arifle_MX_SW_F", "", 0 },
		//	{ "arifle_MX_SW_Black_F", "", 0 },
		//	{ "LMG_Mk200_F", "", 0 },
		//	{ "LMG_Zafir_F", "", 0 },
		//	{ "srifle_EBR_F", "", 0 },
		//	{ "srifle_DMR_01_F", "", 0 },
			{ "srifle_GM6_F", "", 0 },
			{ "srifle_GM6_camo_F", "", 0 },
			{ "srifle_LRR_F", "", 0 },
			{ "srifle_LRR_camo_F", "", 0 },
			{ "launch_RPG32_F", "", 0 },
			{ "launch_Titan_F", "", 0 },
			{ "launch_Titan_short_F", "", 0 },
			{ "launch_NLAW_F", "", 0 },
		//	{ "optic_MRD", "", 0 },
		//	{ "optic_Yorris", "", 0 },
		//	{ "optic_Aco", "", 0 },
		//	{ "optic_Holosight", "", 0 },
		//	{ "optic_Arco", "", 0 },
		//	{ "optic_Hamr", "", 0 },
		//	{ "optic_MRCO", "", 0 },
		//	{ "optic_SOS", "", 0 },
		//	{ "optic_DMS", "", 0 },
			{ "optic_LRPS", "", 0 },
			{ "optic_NVS", "", 0 },
			{ "optic_Nightstalker", "", 0 },
			{ "optic_tws", "", 0 },
			{ "optic_tws_mg", "", 0 },
			{ "optic_AMS", "", 0 },
			{ "optic_AMS_khk", "", 0 },
			{ "optic_AMS_snd", "", 0 },
			{ "optic_KHS_blk", "", 0 },
			{ "optic_KHS_hex", "", 0 },
			{ "optic_KHS_old", "", 0 },
			{ "optic_KHS_tan", "", 0 },
			{ "bipod_01_F_snd", "", 0 },
			{ "bipod_01_F_blk", "", 0 },
			{ "bipod_01_F_mtp", "", 0 },
			{ "bipod_02_F_blk", "", 0 },
			{ "bipod_02_F_tan", "", 0 },
			{ "bipod_02_F_hex", "", 0 },
			{ "bipod_03_F_blk", "", 0 },
			{ "bipod_03_F_oli", "", 0 },
			{ "muzzle_snds_L", "", 0 },
			{ "muzzle_snds_M", "", 0 },
			{ "muzzle_snds_H", "", 0 },
			{ "muzzle_snds_H_MG", "", 0 },
			{ "muzzle_snds_B", "", 0 },
			{ "acc_flashlight", "", 0 },
			{ "acc_pointer_IR", "", 0 },
		//	{ "9Rnd_45ACP_Mag", "", 0 },
		//	{ "11Rnd_45ACP_Mag", "", 0 },
		//	{ "6Rnd_45ACP_Cylinder", "", 0 },
		//	{ "30Rnd_45ACP_Mag_SMG_01", "", 0 },
		//	{ "30Rnd_45ACP_Mag_SMG_01_tracer_green", "", 0 },
		//	{ "16Rnd_9x21_Mag", "", 0 },
		//  { "30Rnd_9x21_Mag", "", 0 },
		//	{ "20Rnd_556x45_UW_mag", "", 0 },
		//	{ "30Rnd_556x45_Stanag", "", 0 },
		//	{ "30Rnd_556x45_Stanag_Tracer_Red", "", 0 },
		//	{ "30Rnd_556x45_Stanag_Tracer_Green", "", 0 },
		//	{ "30Rnd_556x45_Stanag_Tracer_Yellow", "", 0 },
		//	{ "30Rnd_65x39_caseless_green", "", 0 },
		//	{ "30Rnd_65x39_caseless_green_mag_Tracer", "", 0 },
		//	{ "30Rnd_65x39_caseless_mag", "", 0 },
		//	{ "30Rnd_65x39_caseless_mag_Tracer", "", 0 },
		//	{ "100Rnd_65x39_caseless_mag", "", 0 },
		//	{ "1Rnd_HE_Grenade_shell", "", 0 },
		//	{ "3Rnd_HE_Grenade_shell", "", 0 },
		//	{ "UGL_FlareWhite_F", "", 0 },
		//	{ "UGL_FlareGreen_F", "", 0 },
			{ "UGL_FlareRed_F", "", 0 },
			{ "UGL_FlareYellow_F", "", 0 },
			{ "UGL_FlareCIR_F", "", 0 },
		//	{ "3Rnd_UGL_FlareWhite_F", "", 0 },
		//	{ "3Rnd_UGL_FlareGreen_F", "", 0 },
		//	{ "3Rnd_UGL_FlareRed_F", "", 0 },
		//	{ "3Rnd_UGL_FlareYellow_F", "", 0 },
		//	{ "3Rnd_UGL_FlareCIR_F", "", 0 },
		//	{ "1Rnd_Smoke_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeRed_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeGreen_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeYellow_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokePurple_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeBlue_Grenade_shell", "", 0 },
		//	{ "1Rnd_SmokeOrange_Grenade_shell", "", 0 },
		//	{ "3Rnd_Smoke_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeRed_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeGreen_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeYellow_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokePurple_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeBlue_Grenade_shell", "", 0 },
		//	{ "3Rnd_SmokeOrange_Grenade_shell", "", 0 },
		//	{ "200Rnd_65x39_cased_Box", "", 0 },
		//	{ "200Rnd_65x39_cased_Box_Tracer", "", 0 },
		//	{ "150Rnd_762x54_Box", "", 0 },
		//	{ "150Rnd_762x54_Box_Tracer", "", 0 },
		//	{ "10Rnd_762x54_Mag", "", 0 },
		//	{ "20Rnd_762x51_Mag", "", 0 },
			{ "5Rnd_127x108_Mag", "", 0 },
			{ "5Rnd_127x108_APDS_Mag", "", 0 },
			{ "7Rnd_408_Mag", "", 0 },
			{ "RPG32_F", "", 0 },
			{ "RPG32_HE_F", "", 0 },
			{ "Titan_AP", "", 0 },
			{ "Titan_AT", "", 0 },
			{ "Titan_AA", "", 0 },
			{ "NLAW_F", "", 0 }
		};
	};
	class marksmen_cop
	{
		name = "Armurerie Level 3-6 (Marksmen DLC)";
		side = "cop";
		license = "";
		level = 3;
		msg = "Vous n'avez pas le level requis.";
		items[] =
		{
			{ "srifle_DMR_02_F", "", 0 },
			{ "srifle_DMR_02_camo_F", "", 0 },
			{ "srifle_DMR_02_sniper_F", "", 0 },
			{ "MMG_02_black_F", "", 0 },
			{ "MMG_02_camo_F", "", 0 },
			{ "MMG_02_sand_F", "", 0 },
			{ "srifle_DMR_03_F", "", 0 },
			{ "srifle_DMR_03_khaki_F", "", 0 },
			{ "srifle_DMR_03_multicam_F", "", 0 },
			{ "srifle_DMR_03_tan_F", "", 0 },
			{ "srifle_DMR_03_woodland_F", "", 0 },
			{ "srifle_DMR_06_camo_F", "", 0 },
			{ "srifle_DMR_06_olive_F", "", 0 },
			{ "srifle_DMR_05_blk_F", "", 0 },
			{ "srifle_DMR_05_hex_F", "", 0 },
			{ "srifle_DMR_05_tan_F", "", 0 },
			{ "MMG_01_hex_F", "", 0 },
			{ "MMG_01_tan_F", "", 0 },
			{ "srifle_DMR_04_F", "", 0 },
			{ "srifle_DMR_04_Tan_F", "", 0 },
			{ "muzzle_snds_338_black", "", 0 },	 //.338 mm
			{ "muzzle_snds_338_green", "", 0 },	 //.338 mm
			{ "muzzle_snds_338_sand", "", 0 },	 //.338 mm
			{ "muzzle_snds_B", "", 0 },			 //7,62 mm
			{ "muzzle_snds_93mmg", "", 0 },		 //9,3 mm
			{ "muzzle_snds_93mmg_tan", "", 0 },	 //9,3 mm
			{ "optic_AMS", "", 0 },
			{ "optic_AMS_khk", "", 0 },
			{ "optic_AMS_snd", "", 0 },
			{ "optic_KHS_blk", "", 0 },
			{ "optic_KHS_hex", "", 0 },
			{ "optic_KHS_old", "", 0 },
			{ "optic_KHS_tan", "", 0 },
			{ "optic_NVS", "", 0 },
			{ "bipod_01_F_mtp", "", 0 },
			{ "bipod_01_F_snd", "", 0 },
			{ "bipod_01_F_blk", "", 0 },
			{ "bipod_02_F_blk", "", 0 },
			{ "bipod_02_F_tan", "", 0 },
			{ "bipod_02_F_hex", "", 0 },
			{ "bipod_03_F_blk", "", 0 },
			{ "bipod_03_F_oli", "", 0 },
			{ "acc_flashlight", "", 0 },
			{ "acc_pointer_IR", "", 0 },
			{ "10Rnd_338_Mag", "", 0 },
			{ "130Rnd_338_Mag", "", 0 },
			{ "20Rnd_762x51_Mag", "", 0 },
			{ "10Rnd_93x64_DMR_05_Mag", "", 0 },
			{ "150Rnd_93x64_Mag", "", 0 },
			{ "10Rnd_127x54_Mag", "", 0 }
		};
	}; 
};